---
platform: linux

image_resource:
  type: docker-image
  source: {repository: concourse/static-golang}

inputs:
- name: github-tags-resource
  path: gopath/src/github.com/ecsteam/github-tags-resource

outputs:
- name: built-resource

run:
  path: gopath/src/github.com/ecsteam/github-tags-resource/scripts/ci
