---
resources:
- name: github-tags-resource
  type: git
  source:
    uri: git@github.com:ECSTeam/github-tags-resource.git
    private_key: {{github-private-key}}
- name: resource-version
  type: semver
  source:
    driver: git
    uri: git@github.com:ECSTeam/github-tags-resource.git
    branch: version
    file: version
    private_key: {{github-private-key}}
    initial_version: 1.0.0
- name: docker-hub
  type: docker-image
  source:
    repository: ecsteam/github-tags-resource
    email: {{docker-hub-email}}
    username: {{docker-hub-username}}
    password: {{docker-hub-password}}

jobs:
- name: build-assets
  public: true
  plan:
  - get: github-tags-resource
    trigger: true
  - get: resource-version
  - task: build-assets
    file: github-tags-resource/build.yml
  - put: docker-hub
    params:
      build: built-resource
      tag: resource-version/number
      tag_as_latest: true
  - put: resource-version
    params: {bump: patch}
